### ISSUE TITLE
Review 2021-02-02

### ISSUE THREAD

**Issue by mozey** [stock2shop/cart#1]
@flumonion 

1.
I suggest dropping the word "Headless" from the description.
[Headless software](https://en.wikipedia.org/wiki/Headless_software): *"...capable of working on a device without a graphical user interface"*. This repo is intended for use in a Web Browser.

2.
As per [customelements](https://developers.google.com/web/fundamentals/web-components/customelements), custom tags *"...must contain a dash (-). So `<x-tags>`, `<my-element>`, and `<my-awesome-app>` are all valid names, while `<tabs>` and `<foo_bar>` are not"*. That said, it probably makes sense to keep them as short as possible (two words). I suggest the following:
- **s2s-price** sku="abc" ...
- **s2s-qty** sku="abc" ...
- **s2s-add** sku="abc" ...
This component consists of an input with type number, plus and minus buttons, and a button to add to cart?
- **s2s-cart**
Display list of cart items and checkout button
- **s2s-total** currency="USD"
Current total of item in cart
- **s2s-login**
Display [login box](https://b2b.stock2shop.com/login.php)

**Comment by mozey** [comment]
3.

For the JSON API I suggest we create [server.go](https://github.com/stock2shop/cart/issues/4) file in this repo
- Developers can `cd stock2shop/cart && go run server.go` then hit localhost instead of x.stock2shop.com
- Defines all the routes that might be called by `s2s-cart.js`
- Something [like this](https://github.com/mozey/httprouter-example/blob/master/main.go), but even more simplified. A simple [file server](https://github.com/mozey/ts/blob/main/webcomponent/server.go) could do, although defining the routes up front would be wise.
- Implements [mocks](https://martinfowler.com/articles/mocksArentStubs.html#TheDifferenceBetweenMocksAndStubs) that can verify the behavior of the cart

**Comment by flumonion** [comment]
points 1 and 2 covered in #5 
Have a look and let me know.
